{{- if .Values.secrets }}
apiVersion: v1
metadata:
  name: {{ include "m365-exporter.fullname" . }}
  labels:
    {{- include "m365-exporter.labels" . | nindent 4 }}
kind: Secret
data:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ tpl $value $ | b64enc | quote }}
  {{- end }}
type: Opaque
{{- end }}
