{
 "title": "Intune Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(m365_intune_device_compliance,tenant)"
    }
   },
   {
    "name": "opeartingsystem",
    "query": {
     "query": "label_values(m365_intune_device_count,os_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_intune_device_compliance{type=\"all\",tenant=~\"$tenant\"}) by (tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other States",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(m365_intune_device_compliance{type!~\"all|compliant|noncompliant\",tenant=\"$tenant\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "m365_intune_device_compliance{tenant=\"$tenant\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Compliant",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_intune_device_compliance{type=\"compliant\",tenant=\"$tenant\"}) by (tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Compliant",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_intune_device_compliance{type=\"noncompliant\",tenant=\"$tenant\"}) by (tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operating Systems || $opeartingsystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "opeartingsystem",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "m365_intune_device_count{os_name=~\"$opeartingsystem\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}