{
 "title": "M365 License Overview",
 "tags": [
  "opsstack",
  "m365"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "query": {
     "query": "label_values(m365_license_total, tenant)"
    }
   },
   {
    "name": "license",
    "query": {
     "query": "label_values(m365_license_total{tenant=\"$tenant\"}, license)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "License Names",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "[Product names and service plan identifiers for licensing](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference)"
   }
  },
  {
   "title": "License Status",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "### Enabled\n\nThe number of units that are enabled for the active subscription of the service SKU.\n\n### Warning\n\nThe number of units that are in warning status. When the subscription of the service SKU has expired, the customer has a grace period to renew their subscription before it is cancelled (moved to a suspended state).\n\n### Suspended\n\nThe number of units that are suspended because the subscription of the service SKU has been cancelled. The units cannot be assigned but can still be reactivated before they are deleted."
   }
  },
  { "title": "$license", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "license" },
  {
   "title": "License Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_license_status{tenant=\"$tenant\", license=~\"$license\"}) by (tenant, license)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_license_current{tenant=\"$tenant\", license=~\"$license\"}) by (tenant, license) / avg(m365_license_total{tenant=\"$tenant\", license=~\"$license\",status=\"enabled\"}) by (tenant, license)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Current Licenses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_license_current{tenant=\"$tenant\", license=~\"$license\"}) by (tenant, license)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Total Licenses (enabled)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_license_total{tenant=\"$tenant\",license=~\"$license\", status=\"enabled\"}) by (tenant, license)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Total Licenses (warning)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_license_total{tenant=\"$tenant\",license=~\"$license\", status=\"warning\"}) by (tenant, license)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "License Usage over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(m365_license_current{tenant=~\"$tenant\",license=~\"$license\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License Total over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(m365_license_total{tenant=~\"$tenant\",license=~\"$license\",status=\"enabled\"}) by (tenant,license,status)",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "avg(m365_license_total{tenant=~\"$tenant\",license=~\"$license\",status=\"warning\"}) by (tenant,license,status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}