{
 "title": "OneDrive / Sharepoint",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Sharepoint Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(m365_onedrive_used_bytes{driveType=\"documentLibrary\"}) - sum(m365_onedrive_deleted_bytes{driveType=\"documentLibrary\"})",
     "legendFormat": "Sharepoint Usage"
    }
   ]
  },
  {
   "title": "OneDrive Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(m365_onedrive_used_bytes{driveType=\"business\"}) - sum(m365_onedrive_deleted_bytes{driveType=\"business\"})",
     "legendFormat": "Sharepoint Usage"
    }
   ]
  },
  {
   "title": "No. of Sharepoint drives < 20%",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"} - m365_onedrive_used_bytes{driveType=\"documentLibrary\"}) / on(owner,driveID)m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"}) < 0.2) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of User drives < 20%",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((m365_onedrive_total_available_bytes{driveType=\"business\"} - m365_onedrive_used_bytes{driveType=\"business\"}) / on(owner)m365_onedrive_total_available_bytes{driveType=\"business\"}) < 0.2) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total OneDrives we see",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(m365_onedrive_total_available_bytes) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sharepoint Document Libraries",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"} - on(owner,driveID)m365_onedrive_used_bytes{driveType=\"documentLibrary\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"} - m365_onedrive_used_bytes{driveType=\"documentLibrary\"}) / on(owner,driveID)m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": " ((m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"} - m365_onedrive_used_bytes{driveType=\"documentLibrary\"}) / on(owner,driveID)m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"}) - ((m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"} offset $__range - m365_onedrive_used_bytes{driveType=\"documentLibrary\"} offset $__range) / on(owner,driveID)m365_onedrive_total_available_bytes{driveType=\"documentLibrary\"} offset $__range)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "User Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "User personal oneDrives",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "m365_onedrive_total_available_bytes{driveType=\"business\"} - on(owner)m365_onedrive_used_bytes{driveType=\"business\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(m365_onedrive_total_available_bytes{driveType=\"business\"} - m365_onedrive_used_bytes{driveType=\"business\"}) / on(owner)m365_onedrive_total_available_bytes{driveType=\"business\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}