{
 "title": "M365 Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(m365_service_health,tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Achieved Secure Score",
   "type": "gauge",
   "description": "Secure score in percent",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (tenant) (m365_securescore_current{tenant=\"${tenant}\"} / m365_securescore_max{tenant=\"${tenant}\"} * 100)"
    }
   ]
  },
  {
   "title": "Raw scores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "max by (tenant, __name__) (m365_securescore_current{tenant=\"${tenant}\"})",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "max by (tenant,__name__) (m365_securescore_max)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Intune Device Compliance",
   "type": "gauge",
   "description": "Intune Device Compliance in percent",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg (m365_intune_device_compliance{type=\"noncompliant\", tenant=~\"$tenant\"}) by (tenant) / avg (m365_intune_device_compliance{type=\"all\", tenant=~\"$tenant\"}) by (tenant) * 100)"
    }
   ]
  },
  {
   "title": "Service Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "m365_service_health{tenant=\"${tenant}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Azure AD Connect Sync Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_adsync_on_premises_sync_enabled{tenant=\"$tenant\"}) by (tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entra ID Sync Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(m365_adsync_on_premises_sync_error) by (error_bucket,sync_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Azure AD Connect Sync",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "avg(m365_adsync_on_premises_last_sync_date_time{tenant=\"$tenant\"}) by (tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "M365 Licences",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(m365_license_current{tenant=\"$tenant\"}) by (license) / avg(m365_license_total{tenant=\"$tenant\",status=\"enabled\"}) by (license)",
     "legendFormat": "{{license}}"
    }
   ]
  },
  {
   "title": "Groups with License Assignment Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "avg(m365_license_group_errors) by (group_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Advisories & Incidents",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "m365_service_health_issue == 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Closed Advisories & Incidents",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "m365_service_health_issue == 0", "legendFormat": "__auto" }
   ]
  }
 ]
}